create table boards
(
    id           integer generated by default as identity,
    created_at   timestamp(6) not null,
    created_by   bytea        not null,
    updated_at   timestamp(6),
    updated_by   bytea,
    description  varchar(500),
    is_hidden    boolean      not null,
    start_number integer      not null,
    title        varchar(100) not null,
    version      bigint       not null,
    document_id  integer      not null,
    primary key (id)
);

create table calculations
(
    number      integer generated by default as identity,
    created_at  timestamp(6) not null,
    created_by  bytea        not null,
    updated_at  timestamp(6),
    updated_by  bytea,
    command     varchar(255) not null,
    description varchar(500),
    is_hidden   boolean      not null,
    version     bigint       not null,
    document_id integer      not null,
    primary key (number)
);

create table documents
(
    id          integer generated by default as identity,
    created_at  timestamp(6) not null,
    created_by  bytea        not null,
    updated_at  timestamp(6),
    updated_by  bytea,
    description varchar(255),
    is_hidden   boolean      not null,
    title       varchar(100) not null,
    version     bigint       not null,
    primary key (id)
);

create table how_to_calculate
(
    id                           integer generated by default as identity,
    how_to_calculate_description varchar(500) not null,
    version                      bigint       not null,
    indicator_id                 integer      not null,
    primary key (id)
);

create table indicators
(
    id                         integer generated by default as identity,
    created_at                 timestamp(6) not null,
    created_by                 bytea        not null,
    updated_at                 timestamp(6),
    updated_by                 bytea,
    indicator_type             smallint     not null check (indicator_type between 0 and 2),
    is_hidden                  boolean      not null,
    name                       varchar(255) not null,
    type                       smallint     not null check (type between 0 and 2),
    unit                       smallint     not null check (unit between 0 and 2),
    version                    bigint       not null,
    board_id                   integer      not null,
    translation_id             integer,
    translation_description_id integer,
    primary key (id)
);

create table translations
(
    id      integer generated by default as identity,
    en      varchar(1000) not null,
    fa      varchar(1000) not null,
    version bigint        not null,
    primary key (id)
);


alter table if exists boards
    drop constraint if exists UK6i5fjlcog8bjfp0dwno1f36g6;

alter table if exists boards
    add constraint UK6i5fjlcog8bjfp0dwno1f36g6 unique (start_number);

alter table if exists indicators
    drop constraint if exists UKrf22yxhbgy37p0y6ex8iqlvn0;

alter table if exists indicators
    add constraint UKrf22yxhbgy37p0y6ex8iqlvn0 unique (translation_id);

alter table if exists indicators
    drop constraint if exists UKkixo3fmlrsiqqa825i7veda0g;

alter table if exists indicators
    add constraint UKkixo3fmlrsiqqa825i7veda0g unique (translation_description_id);

alter table if exists boards
    add constraint document_id_fk
        foreign key (document_id)
            references documents;

alter table if exists calculations
    add constraint document_id_fk
        foreign key (document_id)
            references documents;

alter table if exists how_to_calculate
    add constraint indicator_id_fk
        foreign key (indicator_id)
            references indicators;

alter table if exists indicators
    add constraint board_id_fk
        foreign key (board_id)
            references boards;

alter table if exists indicators
    add constraint translation_id_fk
        foreign key (translation_id)
            references translations;

alter table if exists indicators
    add constraint translation_description_id_fk
        foreign key (translation_description_id)
            references translations;
